-- First deployable MariaDB schema for accounts, spaces, and inventory.
-- UUIDs are generated by the backend and stored in canonical text form.
-- Destructive operations are deferred until retention rules are defined.

CREATE TABLE accounts (
    id CHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    display_name VARCHAR(255) NOT NULL,
    is_system_admin BOOLEAN NOT NULL DEFAULT FALSE,
    created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    PRIMARY KEY (id),
    CONSTRAINT chk_accounts_display_name CHECK (CHAR_LENGTH(TRIM(display_name)) > 0)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE spaces (
    id CHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    name VARCHAR(255) NOT NULL,
    owner_account_id CHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    PRIMARY KEY (id),
    KEY idx_spaces_owner (owner_account_id),
    CONSTRAINT fk_spaces_owner FOREIGN KEY (owner_account_id) REFERENCES accounts (id),
    CONSTRAINT chk_spaces_name CHECK (CHAR_LENGTH(TRIM(name)) > 0)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE space_memberships (
    space_id CHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    account_id CHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    PRIMARY KEY (space_id, account_id),
    KEY idx_space_memberships_account (account_id),
    CONSTRAINT fk_space_memberships_space FOREIGN KEY (space_id) REFERENCES spaces (id),
    CONSTRAINT fk_space_memberships_account FOREIGN KEY (account_id) REFERENCES accounts (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE space_permission_grants (
    space_id CHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    account_id CHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    permission_code VARCHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    PRIMARY KEY (space_id, account_id, permission_code),
    CONSTRAINT fk_space_grants_membership FOREIGN KEY (space_id, account_id)
        REFERENCES space_memberships (space_id, account_id),
    CONSTRAINT chk_space_grants_permission CHECK (permission_code IN (
        'collections_read', 'collections_write',
        'acquisitions_read', 'acquisitions_write',
        'finance_read', 'finance_write',
        'documents_read', 'documents_write'
    ))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE inventory_counters (
    space_id CHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    next_number BIGINT UNSIGNED NOT NULL DEFAULT 1,
    PRIMARY KEY (space_id),
    CONSTRAINT fk_inventory_counters_space FOREIGN KEY (space_id) REFERENCES spaces (id),
    CONSTRAINT chk_inventory_counters_next CHECK (next_number > 0)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE inventory_items (
    id CHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    space_id CHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    inventory_number BIGINT UNSIGNED NOT NULL,
    name VARCHAR(255) NOT NULL,
    revision BIGINT UNSIGNED NOT NULL DEFAULT 1,
    created_by_account_id CHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    PRIMARY KEY (id),
    UNIQUE KEY uq_inventory_items_space_number (space_id, inventory_number),
    KEY idx_inventory_items_creator (created_by_account_id),
    CONSTRAINT fk_inventory_items_space FOREIGN KEY (space_id) REFERENCES spaces (id),
    CONSTRAINT fk_inventory_items_creator FOREIGN KEY (created_by_account_id) REFERENCES accounts (id),
    CONSTRAINT chk_inventory_items_number CHECK (inventory_number > 0),
    CONSTRAINT chk_inventory_items_revision CHECK (revision > 0),
    CONSTRAINT chk_inventory_items_name CHECK (CHAR_LENGTH(TRIM(name)) > 0)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE inventory_transfers (
    id CHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    item_id CHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    source_space_id CHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    destination_space_id CHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    source_inventory_number BIGINT UNSIGNED NOT NULL,
    destination_inventory_number BIGINT UNSIGNED NOT NULL,
    actor_account_id CHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    transferred_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    PRIMARY KEY (id),
    KEY idx_inventory_transfers_item_date (item_id, transferred_at),
    KEY idx_inventory_transfers_source (source_space_id),
    KEY idx_inventory_transfers_destination (destination_space_id),
    KEY idx_inventory_transfers_actor (actor_account_id),
    CONSTRAINT fk_inventory_transfers_item FOREIGN KEY (item_id) REFERENCES inventory_items (id),
    CONSTRAINT fk_inventory_transfers_source FOREIGN KEY (source_space_id) REFERENCES spaces (id),
    CONSTRAINT fk_inventory_transfers_destination FOREIGN KEY (destination_space_id) REFERENCES spaces (id),
    CONSTRAINT fk_inventory_transfers_actor FOREIGN KEY (actor_account_id) REFERENCES accounts (id),
    CONSTRAINT chk_inventory_transfers_distinct_spaces CHECK (source_space_id <> destination_space_id),
    CONSTRAINT chk_inventory_transfers_source_number CHECK (source_inventory_number > 0),
    CONSTRAINT chk_inventory_transfers_destination_number CHECK (destination_inventory_number > 0)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
